# Generated by Django 4.0.2 on 2022-06-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acDate', models.DateTimeField(db_column='acDate', max_length=50)),
                ('acBrand', models.CharField(db_column='acBrand', max_length=50)),
                ('acPoint', models.IntegerField(db_column='acPoint', default=300)),
            ],
            options={
                'db_table': 'pointinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('phoneNum', models.CharField(db_column='phoneNum', max_length=11, primary_key=True, serialize=False)),
                ('userName', models.CharField(db_column='userName', max_length=50)),
                ('userId', models.CharField(db_column='userId', max_length=50)),
                ('userPass', models.CharField(db_column='userPass', max_length=50)),
            ],
            options={
                'db_table': 'userinfo',
                'managed': False,
            },
        ),
    ]
